var searchData=
[
  ['cartesian_5fcommunicator_0',['cartesian_communicator',['../structpartensor_1_1v1_1_1cartesian__communicator.html#a5429f5477ab7a59cd38e180ee6f0145f',1,'partensor::v1::cartesian_communicator::cartesian_communicator(cartesian_communicator const &amp;comm, std::vector&lt; int &gt; const &amp;keep)'],['../structpartensor_1_1v1_1_1cartesian__communicator.html#a9d0bfe1c2d42904de0dec275c7093183',1,'partensor::v1::cartesian_communicator::cartesian_communicator(communicator const &amp;comm, cartesian_topology const &amp;dims, bool reorder=true)']]],
  ['cartesian_5fdimension_1',['cartesian_dimension',['../structpartensor_1_1v1_1_1cartesian__dimension.html#ab82c6b7812cfe28abec02ab368c7f055',1,'partensor::v1::cartesian_dimension']]],
  ['cartesian_5ftopology_2',['cartesian_topology',['../structpartensor_1_1v1_1_1cartesian__topology.html#a0c134ab069a7c60cf543ac7d4be1d4b2',1,'partensor::v1::cartesian_topology']]],
  ['choose_5fnormilization_5ffactor_3',['choose_normilization_factor',['../Normalize_8hpp.html#ab33d31598d5ab939685b67b368e08336',1,'partensor::v1']]],
  ['communicator_4',['communicator',['../structpartensor_1_1v1_1_1communicator.html#a85ecb5032942a695e1293c0e92dcc16d',1,'partensor::v1::communicator']]],
  ['computesvd_5',['ComputeSVD',['../NesterovMNLS_8hpp.html#adcb68ae170ae16beafc4f0b95d0da9aa',1,'partensor::v1']]],
  ['cpd_6',['cpd',['../Cpd_8hpp.html#a58c1bb98fe3f978ec3ef23c4340270f1',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#ab77d6e4f611dc4970322fc001c1e36eb',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize &gt; const &amp;true_paths, std::array&lt; std::string, TnsSize &gt; const &amp;init_paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#a9c630f8a6fc7f36f964f7335cfb9bc47',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#ad3b704138563f6f8ae5131c9f99bae1f',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths)'],['../Cpd_8hpp.html#a6978a9cae34ae979c58df5d036199bae',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path)'],['../Cpd_8hpp.html#ad557de916a422a94f24a1868fd88842e',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, MatrixArray&lt; Tensor_ &gt; const &amp;factorsInit)'],['../Cpd_8hpp.html#ae6934c995323fbad8fab1f155234d9f3',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#a636c32b0d3ea8af38607e9f87a122b57',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R)'],['../Cpd_8hpp.html#a3e2a50f4dfed8282ab8bc6c46f34bf66',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options, MatrixArray&lt; Tensor_ &gt; const &amp;factorsInit)']]],
  ['cpddimtree_7',['cpdDimTree',['../CpdDimTree_8hpp.html#a3feb49d63287c26faf032cef7c54a40e',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, MatrixArray_ const &amp;factorsInit)'],['../CpdDimTree_8hpp.html#a1a59eb1621048d34d3c203f2cda80d22',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../CpdDimTree_8hpp.html#a92a8f3fe0f8e068a862a019f142c822e',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths)'],['../CpdDimTree_8hpp.html#a5fc18b9ef79d9be94c64105bdbd64882',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../CpdDimTree_8hpp.html#a57813e4df333852557523383f43a9b8b',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path)'],['../CpdDimTree_8hpp.html#af48c576b0f8d9b3a686d2b59b9a180ee',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options, MatrixArray_ const &amp;factorsInit)'],['../CpdDimTree_8hpp.html#a52efa51cb3ffd8c5e0c02f202433313d',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../CpdDimTree_8hpp.html#a1fb3c0c61c3a5cdec0d0b10ac14b67e5',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R)']]],
  ['create_8',['Create',['../structpartensor_1_1ExprTree.html#aa6a0bb0525868123c4feeef648cb0248',1,'partensor::ExprTree::Create(std::array&lt; int, RootExprNode::LabelSetSize &gt; &amp;aLabelSet, Array const &amp;aTnsDims, int const R, Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt; const &amp;aTnsX)'],['../structpartensor_1_1ExprTree.html#a60901f60176982e21091ca0ed64c4a50',1,'partensor::ExprTree::Create(Array const &amp;aTnsDims, int const R, ExprNode &amp;expr)']]],
  ['create_5ffiber_5fgrid_9',['create_fiber_grid',['../ParallelWrapper_8hpp.html#a872376aaf909fa777d121a802f4aa277',1,'partensor::v1']]],
  ['create_5flayer_5fgrid_10',['create_layer_grid',['../ParallelWrapper_8hpp.html#ac6da1e9e89fbcaf0f546c9e30cbbccfb',1,'partensor::v1']]],
  ['cwiseprod_11',['CwiseProd',['../CwiseProd_8hpp.html#a8b4954e7f53f0c32c7ee8af7c488f263',1,'partensor::v1']]]
];
