var searchData=
[
  ['cartesian_5fcommunicator',['cartesian_communicator',['../structpartensor_1_1v1_1_1cartesian__communicator.html#a9d0bfe1c2d42904de0dec275c7093183',1,'partensor::v1::cartesian_communicator::cartesian_communicator(communicator const &amp;comm, cartesian_topology const &amp;dims, bool reorder=true)'],['../structpartensor_1_1v1_1_1cartesian__communicator.html#a5429f5477ab7a59cd38e180ee6f0145f',1,'partensor::v1::cartesian_communicator::cartesian_communicator(cartesian_communicator const &amp;comm, std::vector&lt; int &gt; const &amp;keep)']]],
  ['cartesian_5fdimension',['cartesian_dimension',['../structpartensor_1_1v1_1_1cartesian__dimension.html#ab82c6b7812cfe28abec02ab368c7f055',1,'partensor::v1::cartesian_dimension']]],
  ['cartesian_5ftopology',['cartesian_topology',['../structpartensor_1_1v1_1_1cartesian__topology.html#a0c134ab069a7c60cf543ac7d4be1d4b2',1,'partensor::v1::cartesian_topology']]],
  ['choose_5fnormilization_5ffactor',['choose_normilization_factor',['../Normalize_8hpp.html#ab33d31598d5ab939685b67b368e08336',1,'partensor::v1']]],
  ['communicator',['communicator',['../structpartensor_1_1v1_1_1communicator.html#a85ecb5032942a695e1293c0e92dcc16d',1,'partensor::v1::communicator']]],
  ['computesvd',['ComputeSVD',['../NesterovMNLS_8hpp.html#adcb68ae170ae16beafc4f0b95d0da9aa',1,'partensor::v1']]],
  ['cpd',['cpd',['../Cpd_8hpp.html#adc43f2821f9d28f52bcee543e5876f3a',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R)'],['../Cpd_8hpp.html#ab61d764733b9ab4f4b8f12d0001f9fc8',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#aba13c0dc3618ffaf7fdf1ab759b1dc49',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, MatrixArray&lt; Tensor_ &gt; const &amp;factorsInit)'],['../Cpd_8hpp.html#a42fb4eba0063a7df2a7df9f7e2f1c0ad',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options, MatrixArray&lt; Tensor_ &gt; const &amp;factorsInit)'],['../Cpd_8hpp.html#ae0952f087088500a001390eec009ee80',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path)'],['../Cpd_8hpp.html#a2679309a586b518566f11ebcce367995',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#a5f7a60f9d5dae366e34c8da1400cdfea',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths)'],['../Cpd_8hpp.html#a75233d4846ed96abd34a523e5c717cf6',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../Cpd_8hpp.html#a8d16093ee34cf4f3e4aac6fa4b5fb499',1,'partensor::cpd(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize &gt; const &amp;true_paths, std::array&lt; std::string, TnsSize &gt; const &amp;init_paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)']]],
  ['cpddimtree',['cpdDimTree',['../CpdDimTree_8hpp.html#af04b15916aeb011d3dacd738f6e3f16f',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R)'],['../CpdDimTree_8hpp.html#acf84e6d7e0bbf7bdb0d9136696a62fd9',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../CpdDimTree_8hpp.html#a32f0ad6a2429265f125d7a1085aa7917',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, MatrixArray_ const &amp;factorsInit)'],['../CpdDimTree_8hpp.html#a9875b71b59fd65ee927049ef65033600',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, Tensor_ const &amp;tnsX, std::size_t const R, Options&lt; Tensor_, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options, MatrixArray_ const &amp;factorsInit)'],['../CpdDimTree_8hpp.html#a14c8bb2814cab2638ce5beb17ae9fc38',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path)'],['../CpdDimTree_8hpp.html#a612e6ca44b2d9505285e6fcf91de2f5f',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::string const &amp;path, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)'],['../CpdDimTree_8hpp.html#af3abb56f4e903a61a3d6ecbd92173973',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths)'],['../CpdDimTree_8hpp.html#a5658495746ad59a90ed91483ce1c09f3',1,'partensor::cpdDimTree(ExecutionPolicy &amp;&amp;, std::array&lt; int, TnsSize &gt; const &amp;tnsDims, std::size_t const R, std::array&lt; std::string, TnsSize+1 &gt; const &amp;paths, Options&lt; Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt;, execution::execution_policy_t&lt; ExecutionPolicy &gt;, DefaultValues &gt; const &amp;options)']]],
  ['create',['Create',['../structpartensor_1_1ExprTree.html#aa6a0bb0525868123c4feeef648cb0248',1,'partensor::ExprTree::Create(std::array&lt; int, RootExprNode::LabelSetSize &gt; &amp;aLabelSet, Array const &amp;aTnsDims, int const R, Tensor&lt; static_cast&lt; int &gt;(TnsSize)&gt; const &amp;aTnsX)'],['../structpartensor_1_1ExprTree.html#a71241d895e58915b4e70ca03e0011018',1,'partensor::ExprTree::Create(Array const &amp;aTnsDims, [[maybe_unused]] int const R, ExprNode &amp;expr)']]],
  ['create_5ffiber_5fgrid',['create_fiber_grid',['../ParallelWrapper_8hpp.html#a872376aaf909fa777d121a802f4aa277',1,'partensor::v1']]],
  ['create_5flayer_5fgrid',['create_layer_grid',['../ParallelWrapper_8hpp.html#ac6da1e9e89fbcaf0f546c9e30cbbccfb',1,'partensor::v1']]],
  ['cwiseprod',['CwiseProd',['../CwiseProd_8hpp.html#a8b4954e7f53f0c32c7ee8af7c488f263',1,'partensor::v1']]]
];
